---
platform: linux
image_resource:
  type: docker-image
  source:
#    repository: springcloud/pipeline-base
    repository: 10.147.108.81:5000/pipeline-base
    insecure_registries: ["10.147.108.81:5000"]
inputs:
  - name: tools
  - name: repo
  - name: version
  - name: m2
outputs:
  - name: out
run:
  path: /bin/bash
  args:
    - tools/concourse/tasks/test-deploy.sh
